//aggregate sales data and counts
   public  class wrapperObject {
   
      public Decimal Barrx_Disposable_Base;
      public Decimal Beacon_Base;
      public Decimal PillCam_Disposable_Base;
      public Decimal Reflux_Disposable_Base;
      public Decimal SmartPill_Disposable_Base;
      public Integer PillCam_SB;
      public Integer SmartPill_Capsules;
      public Integer RFA_Catheters;
      public Integer Bravo_Capsules;

   }